### ISSUE TITLE
Failed to retrieve a request token

### ISSUE THREAD

**Issue by Hi-Angel** [hayamiz/twittering-mode#121]
<kbd>M</kbd>-<kbd>x</kbd> <kbd>twit</kbd> results in messages:

	Failure: /usr/bin/curl exited abnormally (exit-status=60) for POST https://api.twitter.com/oauth/request_token
	twittering-oauth-get-access-token: Failed to retrieve a request token

Looks [similar to this bug](https://github.com/hayamiz/twittering-mode/issues/58), except that I do have the file, mentioned in the `twittering-cert-file` variable.

As an additional information: I've used Ubuntu before, and migrated to Archlinux, and my `~/.emacs` and `~/.emacs.d` are symbolic links to the old partition with Ubuntu. I also tried to do <kbd>M</kbd>-<kbd>x</kbd> <kbd>install-package</kbd> <kbd>twittering-mode</kbd>, but that didn't fix the problem.

**Comment by Hi-Angel** [comment]
Fixed the problem with the steps:

1. <kbd>M</kbd>-<kbd>x</kbd> package-delete <kbd>Enter</kbd>twittering-mode
2. <kbd>M</kbd>-<kbd>x</kbd> package-list-packages
3. <kbd>M</kbd>-<kbd>x</kbd> package-install <kbd>Enter</kbd>twittering-mode
4. <kbd>M</kbd>-<kbd>x</kbd> twit
5. It'd ask for a token, recreate it again.

Closing the issue as it's unable to reproduce anymore.

**Comment by llcc** [comment]
I reinstalled the package, but the problem still exist.

**Comment by fpGHwd** [comment]
Same problem and re-installation dose not work.

**Comment by meechew** [comment]
I am having this issue with a new install.

**Comment by fpGHwd** [comment]
> I am having this issue with a new install.

[trying this:](https://sourceforge.net/p/twmode/mailman/message/31740577/)
`(setq twittering-allow-insecure-server-cert t)`

**Comment by dorneanu** [comment]
> trying this:
>   (setq twittering-allow-insecure-server-cert t)

That fixed the problem.
