### ISSUE TITLE
Add support for Twitter's new 280 character limit

### ISSUE THREAD

**Issue by cfuhrman** [hayamiz/twittering-mode#142]
As of September 2017, Twitter now supports a maximum length of 280 characters.  Modify twittering mode to support the increased character limit.

I will be posting a PR with the modified code shortly.

**Comment by ahungry** [comment]
Is anyone maintaining this package atm?

**Comment by cvmat** [comment]
I have committed support for posting a tweet longer than 140 characters.
It is not so simple. You can see the detail at https://github.com/hayamiz/twittering-mode/pull/143
