### ISSUE TITLE
twittering-update-service-configuration-sentinel: Format "nil" is not supported

### ISSUE THREAD

**Issue by emacsomancer** [hayamiz/twittering-mode#148]
I'm getting no tweets appearing and the error:

````
error in process sentinel: twittering-update-service-configuration-sentinel: Format "nil" is not supported
error in process sentinel: Format "nil" is not supported
````

**Comment by JunpeiAnzai** [comment]
I also faced this issue after upgrading curl version 7.61.0.
One of workaround is to avoid using curl like
```
(setq twittering-connection-type-order '(urllib-https))
```

**Comment by cvmat** [comment]
@emacsomancer I have committed fbdd433de60f0e83f55a6560685409400216a42c that will solve the problem. Please try it.  You can see the detail at #149.

**Comment by emacsomancer** [comment]
@cvmat Thanks! I tried it out and now curl seems to work again.
