### ISSUE TITLE
Unable to get PIN

### ISSUE THREAD

**Issue by manandbytes** [hayamiz/twittering-mode#53]
Twittering-mode is unable to get PIN. Steps to reproduce:

- manandbytes@6c66d9a6bcfe installed (has two commits on top of hayamiz@e454907b9111)
- M-x twit
- temp buffer shows:

    Authorization via OAuth
    1.Allow access by twittering-mode on the below site.
      https://api.twitter.com/oauth/authorize?oauth_token=
    2.After allowing access, the site will display the PIN code.
      Input the PIN code at the below minibuffer.

- in the minibuffer, reply 'y' to 'Open authorization URL in browser?' question
- Firefox shows this message instead of PIN:
    Whoa there!
    There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake.
- minibuffer waits for 'Input PIN code:'

**Comment by mkpankov** [comment]
I have the same issue with current stock ELPA version.

It worked previously for me on other connections and other machines. Here I have proxy, which I configured `twittering-mode` for, but the issue still occurs.

**Comment by mkpankov** [comment]
@manandbytes is there a fix?

**Comment by manandbytes** [comment]
Not sure about specific commit that fixed this, 97ed4410dd994c09081a7a12570adb34f356d87c just works for me now.
