### ISSUE TITLE
OAuth fails on ArchLinux.

### ISSUE THREAD

**Issue by christianlask** [hayamiz/twittering-mode#58]
I use Archlinux and Emacs24. And the twittering-mode.el from the master branch.

When I try M-x twit, I get this error messages:

Failure: /usr/bin/curl exited abnormally (exit-status=60).
Authorization via OAuth failed. Type M-x twit to retry.

What can I do about it?

**Comment by rohitvvv** [comment]
I see this in my mini-buffer when I hit M-x twit in the minibuffer.
" /usr/bin/curl exited  abnormally exit-status=7 "
Is this a new issue?

**Comment by Hi-Angel** [comment]
@rohitvvv yeah, it's a different exit status, and a different issue.
