### ISSUE TITLE
3.0 tag

### ISSUE THREAD

**Issue by AshtonKem** [hayamiz/twittering-mode#95]
With the creation of [melpa stable](http://melpa-stable.milkbox.net/) a lot of people have switched away from melpa for reliability reasons. But it uses tags to decide what version to build, and there currently are no tags for the 3.X series on twittering-mode, thus only the (broken) 2.0 version is available.

**Comment by camdez** [comment]
:+1:

This will only take a couple seconds and it will improve life for a lot users (everyone who installs from MELPA Stable currently gets a broken version due to certificate changes).

```sh
$ git tag -a v3.0.0 -m "3.0.0 release" 27e7f3aab238bd0788fd3b471c645c3ceceb0f13
$ git push origin v3.0.0
```

**Comment by cvmat** [comment]
Thank you @camdez . By using the command, I have added the tag "v3.0.0" to hayamiz/twittering-mode@27e7f3aab238bd0788fd3b471c645c3ceceb0f13 .

But it might not help MELPA users because it includes the obsolete CA certificates...
When I have time, I want to release the latest version as 3.1.0.

**Comment by camdez** [comment]
@cvmat I thought that might be the case but it's a good first step. Thank you!

**Comment by cubranic** [comment]
Can this issue be closed then, @AshtonKem?

**Comment by AshtonKem** [comment]
I believe so, yes. Thank you!

--
Ashton Kemerling
